name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or your preferred Node.js version

    - name: Install dependencies
      run: npm install -g firebase-tools

    - name: Build
      run: npm run build # or your build command

    - name: Deploy to Firebase
      env:
        FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
      run: firebase deploy --only hosting

